### PR TITLE
Ellipse x y radius x radius y

### PR DESCRIPTION
**Pull request by will-moore**
Porting changes from OMERO.figure back to shape-editor.

This includes:
 - Renaming of ellipse attributes from ```cx, cy, rx, ry``` to ```x, y, radiusX, radiusY```
 - Minor fix to the ```stroke-width``` of 2 Rectangles that are hidden from the user (used for click handling) as noticed and tested in https://github.com/ome/omero-figure/pull/213

This is now up to date with what's in OMERO.figure, except for the reverted commits in https://github.com/ome/omero-figure/pull/213 that can be in a future OMERO.figure PR. 

It has already been tested in previous OMERO.figure PRs (primarily https://github.com/ome/omero-figure/pull/190) and https://github.com/ome/omero-figure/pull/213.

### CODE REVIEW

**Comment by will-moore** [comment]
@jburel I guess I need to commit the same changes into the concatenated ```shape-editor.js``` too?

**Comment by jburel** [comment]
I have not modified the build yet so we still have the concatenated file under version control
if you run the build and push it that will be good
Since we have a number of renaming we will have to go for 3.0.0 version

**Comment by will-moore** [comment]
Committed the concatenated shape-editor.js and updated this in https://github.com/ome/omero-figure/pull/220

**Comment by jburel** [comment]
@will-moore can you remove 	your last commit? there is already a ``.gitignore`` on master

**Comment by will-moore** [comment]
Removed last commit.

**Pull request merged**
